CREATE TABLE IF NOT EXISTS items (
    code VARCHAR(10) PRIMARY KEY,
    trading_name VARCHAR(255) NOT NULL,
    market_type VARCHAR(255) DEFAULT NULL,
    sector33_code INTEGER DEFAULT NULL,
    sector33_name VARCHAR(255)  DEFAULT NULL,
    sector17_code INTEGER DEFAULT NULL,
    sector17_name VARCHAR(255)  DEFAULT NULL,
    scale_code INTEGER DEFAULT NULL,
    scale_name VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)